### ISSUE TITLE
可以解答下，可以用于什么场景吗？

### ISSUE THREAD

**Issue by zkj1374960803** [yueshutong/SnowJena#3]
如果需要限流的话，我可以用网关做，为什么要用这个。可以解答一下吗？

**Comment by yueshutong** [comment]
网关是对入口流量进行限制，更多的情况是对特定的服务，比如访问后台MySQL数据库；或特定的代码功能进行限流，比如对外提供的API接口进行限流等。

**Comment by zkj1374960803** [comment]
嗯嗯，明白了
